### ISSUE TITLE
chore: CTRL+C should perform a global shutdown

### ISSUE THREAD

**Issue by francis2tm** [edgenai/edgen#46]
Right now, CTRL+C is only shutting down `edgen_server`'s thread. While tauri's thread keeps alive

**Comment by toschoo** [comment]
This is easy to solve: we just have to call exit when serve returns to main.
However, we should review the shutdown process. At the moment, there is not way for the tauri GUI to initiate a graceful shutdown. It just exits ignoring whatever is going on in edgen_server.

**Comment by toschoo** [comment]
solved with PR #56 (issue #8)
